<?php

liga-grupo-de-acesso
camisa-verde-e-branco
estrela-do-terceiro-milenio
morro-de-casa-verde
perola-negra
imperador-do-ipiranga
leandro-de-itaquera
unidos-de-santa-barbara
unidos-do-peruche
uesp
barroca-zona-sul
camisa-12
colorado-do-bras
dom-bosco-de-itaquera
mocidade-unida-da-mooca
prova-de-fogo
tradicao-albertinense
tup
uirapuru-da-mooca
unidos-de-sao-lucas
uesp
torcida-jovem
liga-grupo-especial
vai-vai
academicos-do-tucuruvi
academicos-do-tatuape
aguia-de-ouro
dragoes-da-real
gavioes-da-fiel
imperio-de-casa-verde
mancha-verde
mocidade-alegre
nene-de-vila-matilde
x-9-paulistana
tom-maior
unidos-de-vila-maria
rosas-de-ouro
bloco-da-ressaca

?>
